// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | EmbedSlice
  | SimpleHeroSlice
  | ContactSlice
  | IconFeatureGridSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Contact → Default → Primary → Socials*
 */
export interface ContactSliceDefaultPrimarySocialsItem {
  /**
   * Social icons field in *Contact → Default → Primary → Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[].social_icons
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social_icons: prismic.SelectField<"instagram" | "linkedin">;

  /**
   * Social link field in *Contact → Default → Primary → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Socials field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<ContactSliceDefaultPrimarySocialsItem>>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Embed → Default → Primary*
 */
export interface EmbedSliceDefaultPrimary {
  /**
   * EmbedField field in *Embed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embed.default.primary.embedfield
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embedfield: prismic.EmbedField;
}

/**
 * Default variation for Embed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Embed*
 */
type EmbedSliceVariation = EmbedSliceDefault;

/**
 * Embed Shared Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Embed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedSlice = prismic.SharedSlice<"embed", EmbedSliceVariation>;

/**
 * Item in *IconFeatureGrid → Default → Primary → Features*
 */
export interface IconFeatureGridSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *IconFeatureGrid → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_grid.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *IconFeatureGrid → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_grid.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IconFeatureGrid → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_grid.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *IconFeatureGrid → Default → Primary*
 */
export interface IconFeatureGridSliceDefaultPrimary {
  /**
   * Features field in *IconFeatureGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_grid.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<IconFeatureGridSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for IconFeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays features in a three-column grid, each column containing an icon, a heading, and a supporting description.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconFeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconFeatureGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconFeatureGrid*
 */
type IconFeatureGridSliceVariation = IconFeatureGridSliceDefault;

/**
 * IconFeatureGrid Shared Slice
 *
 * - **API ID**: `icon_feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconFeatureGridSlice = prismic.SharedSlice<
  "icon_feature_grid",
  IconFeatureGridSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SimpleHero → Default → Primary*
 */
export interface SimpleHeroSliceDefaultPrimary {
  /**
   * Icon field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_hero.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for SimpleHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleHero*
 */
type SimpleHeroSliceVariation = SimpleHeroSliceDefault;

/**
 * SimpleHero Shared Slice
 *
 * - **API ID**: `simple_hero`
 * - **Description**: SimpleHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleHeroSlice = prismic.SharedSlice<
  "simple_hero",
  SimpleHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactSlice,
      ContactSliceDefaultPrimarySocialsItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      EmbedSlice,
      EmbedSliceDefaultPrimary,
      EmbedSliceVariation,
      EmbedSliceDefault,
      IconFeatureGridSlice,
      IconFeatureGridSliceDefaultPrimaryFeaturesItem,
      IconFeatureGridSliceDefaultPrimary,
      IconFeatureGridSliceVariation,
      IconFeatureGridSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SimpleHeroSlice,
      SimpleHeroSliceDefaultPrimary,
      SimpleHeroSliceVariation,
      SimpleHeroSliceDefault,
    };
  }
}
