// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  icon_feature_grid: dynamic(() => import("./IconFeatureGrid")),
  rich_text: dynamic(() => import("./RichText")),
};
